/**
 * MM2 `roster.dat` codec — 48 playable character records × 130 bytes + a
 * 2080-byte global save stream = 8320 bytes total.
 *
 * Format documentation ported from Vairn/MM2 (`EXTRACTED/docs/06-roster-format.md`).
 * Multibyte fields are **little-endian** on disk (the Amiga port byte-swaps
 * word/long fields on load at asm 0x3290). The editor round-trip container
 * stores the global blob as slots 48–63 (16 × 130) of the same file — both
 * views are the same 8320 bytes.
 *
 * VERIFIED against the real fixture `tools/mm2/fixtures/roster_create_test.dat`
 * (a full 8320-byte roster generated by the Vairn/MM2 C++ remake's
 * roster-create test): record 0 decodes to the expected "Sir Felgar" with all
 * documented fields, and encode(decode(file)) reproduces the file byte-exact.
 *
 * Record layout ($82 = 130 bytes):
 *   +$00  11B  name       null-terminated, space-padded
 *   +$0B   1B  town/inn   low7 = town (1..5); bit7 = "in party" flag
 *   +$0C   1B  sex        0 = male, nonzero = female
 *   +$0D   1B  alignment  current (0 Good, 1 Neutral, 2 Evil)
 *   +$0E   1B  race       index into race table
 *   +$0F   1B  class      index into class table
 *   +$10..+$15  6B  current stats: might, int, personality, speed, accuracy, luck
 *   +$16   1B  thievery %
 *   +$17..+$19  3B  secondary skills
 *   +$1A..+$1F  6B  quest / progress flags (not ASM-mapped)
 *   +$20   1B  working level — ASM-confirmed mirror of +$71 (level); see below
 *   +$21   1B  age
 *   +$22   1B  unknown (still not ASM-mapped)
 *   +$23   1B  working spell-level / caster flag — ASM-confirmed mirror of +$72
 *   +$24   1B  armor class (effective)
 *   +$25   1B  food
 *   +$26   1B  condition
 *   +$27   1B  endurance (current)
 *   +$28..+$33   equipped: 6 ids, 6 charges, 6 flags (structure-of-arrays)
 *   +$3A..+$45   backpack: 6 ids, 6 charges, 6 flags (structure-of-arrays)
 *   +$4C..+$57  12B  spell book bitmask (sorc + cleric levels)
 *   +$58  u16le SP max, +$5A u16le SP current, +$5C u16le gems,
 *   +$5E  u16le HP max, +$60 u16le HP temp, +$62 u32le XP, +$66 u32le gold
 *   +$6A..+$73   base alignment/stats/level/spell-level/endurance
 *   +$74  u16le HP current, +$76 u16le temp/score
 *   +$78   1B  script/work flag
 *   +$79   1B  class-quest / guild mask
 *   +$7A..+$81  10B  padding/unknown (mostly zero)
 *
 * **`$1A..$20` quest-flags TODO, resolved for `$20` (ASM-confirmed,
 * `06-roster-format.md`):** bytes `$1A`-`$1F` remain genuine unknowns —
 * Vairn's own doc still calls them "Likely class-quest and world-quest bits
 * ... not ASM-mapped" (kept as `questFlags` below, 6 bytes). Byte `$20` is
 * NOT a quest flag: it is ASM-confirmed as a **working-level mirror** of
 * `+$71` (`level`) — seeded to 1 at character creation (`0x272D6`), synced
 * `$20 -> $71` (not the reverse) by `sync_party_secondary_stats` (`0x4476`),
 * and consumed as the SP multiplier by the Rest routine (`0x19C9A`,
 * `mulu.w $20(a1),d0`). Same story for byte `$23` (paired with `$22`, the
 * genuinely-unknown low byte of the old `$22/$23` LE word this codec used to
 * expose as one field): `$23` is an ASM-confirmed working-spell-level/caster
 * flag mirroring `+$72` (`secondaryLevel`), gated by `tst.b $23(a0)` at
 * `0x19C34` and synced the same way as `$20`. Vairn's doc flags a real
 * ROM/save-drift bug here (stock starters ship with `$20` stuck at `1` while
 * `$71` is higher) — this codec only decodes/round-trips the on-disk bytes,
 * it does not attempt to fix or resync them.
 */

export const ROSTER_CHAR_RECORD_SIZE = 0x82;
export const ROSTER_CHAR_COUNT = 48;
export const ROSTER_GLOBAL_SIZE = 2080;
export const ROSTER_FILE_SIZE = ROSTER_CHAR_COUNT * ROSTER_CHAR_RECORD_SIZE + ROSTER_GLOBAL_SIZE; // 8320

export interface RosterCharacter {
  index: number;
  /** Trimmed display name (NUL/space padding stripped). */
  name: string;
  /** The raw 11-byte name field (preserved verbatim for byte-exact round-trip). */
  nameRaw: Uint8Array;
  town: number;
  inParty: boolean;
  sex: number;
  alignment: number;
  race: number;
  charClass: number;
  stats: { might: number; intelligence: number; personality: number; speed: number; accuracy: number; luck: number };
  thievery: number;
  skills: [number, number, number];
  /** Bytes $1A-$1F (6 bytes). Still not ASM-mapped in Vairn's docs — likely class-quest/world-quest bits, but unresolved. */
  questFlags: number[];
  /** Byte $20. ASM-confirmed working-level mirror of {@link level} (`+$71`), NOT a quest flag — see the module doc for the sync/drift details. */
  workingLevel: number;
  age: number;
  /** Byte $22. Genuinely unknown (low byte of the old combined `$22/$23` word) — not ASM-mapped. */
  unknown22: number;
  /** Byte $23. ASM-confirmed working-spell-level/caster-flag mirror of {@link secondaryLevel} (`+$72`) — see the module doc. */
  workingSpellLevel: number;
  armorClass: number;
  food: number;
  condition: number;
  endurance: number;
  equipped: { ids: number[]; charges: number[]; flags: number[] };
  backpack: { ids: number[]; charges: number[]; flags: number[] };
  spellBook: number[];
  spMax: number;
  spCurrent: number;
  gems: number;
  hpMax: number;
  hpTemp: number;
  experience: number;
  gold: number;
  baseAlignment: number;
  baseStats: { might: number; intelligence: number; personality: number; speed: number; accuracy: number; luck: number };
  level: number;
  secondaryLevel: number;
  baseEndurance: number;
  hpCurrent: number;
  tempWord: number;
  scriptFlag: number;
  classQuestMask: number;
  /** The raw record bytes (everything not explicitly field-mapped). */
  tail: Uint8Array;
}

export interface RosterFile {
  characters: RosterCharacter[];
  /** 2080-byte packed quest/calendar/combat-state blob (opaque round-trip). */
  global: Uint8Array;
}

const u16le = (d: Uint8Array, o: number) => d[o] | (d[o + 1] << 8);
const u32le = (d: Uint8Array, o: number) => (d[o] | (d[o + 1] << 8) | (d[o + 2] << 16) | (d[o + 3] << 24)) >>> 0;

export function decodeRoster(data: Uint8Array): RosterFile {
  if (data.length < ROSTER_FILE_SIZE) {
    throw new Error(`roster.dat: expected >= ${ROSTER_FILE_SIZE} bytes, got ${data.length}`);
  }
  const characters: RosterCharacter[] = [];
  for (let i = 0; i < ROSTER_CHAR_COUNT; i++) {
    const off = i * ROSTER_CHAR_RECORD_SIZE;
    const d = data.subarray(off, off + ROSTER_CHAR_RECORD_SIZE);

    const townByte = d[0x0b];
    const eqBase = 0x28;
    const bpBase = 0x3a;
    const nameRaw = Uint8Array.from(d.subarray(0x00, 0x0b));
    characters.push({
      index: i,
      // eslint-disable-next-line no-control-regex
      name: new TextDecoder('latin1').decode(nameRaw).replace(/[\u0000 ]+$/, ''),
      nameRaw,
      town: townByte & 0x7f,
      inParty: (townByte & 0x80) !== 0,
      sex: d[0x0c],
      alignment: d[0x0d],
      race: d[0x0e],
      charClass: d[0x0f],
      stats: {
        might: d[0x10],
        intelligence: d[0x11],
        personality: d[0x12],
        speed: d[0x13],
        accuracy: d[0x14],
        luck: d[0x15],
      },
      thievery: d[0x16],
      skills: [d[0x17], d[0x18], d[0x19]],
      questFlags: [...d.subarray(0x1a, 0x20)],
      workingLevel: d[0x20],
      age: d[0x21],
      unknown22: d[0x22],
      workingSpellLevel: d[0x23],
      armorClass: d[0x24],
      food: d[0x25],
      condition: d[0x26],
      endurance: d[0x27],
      equipped: {
        ids: [...d.subarray(eqBase, eqBase + 6)],
        charges: [...d.subarray(eqBase + 6, eqBase + 12)],
        flags: [...d.subarray(eqBase + 12, eqBase + 18)],
      },
      backpack: {
        ids: [...d.subarray(bpBase, bpBase + 6)],
        charges: [...d.subarray(bpBase + 6, bpBase + 12)],
        flags: [...d.subarray(bpBase + 12, bpBase + 18)],
      },
      spellBook: [...d.subarray(0x4c, 0x58)],
      spMax: u16le(d, 0x58),
      spCurrent: u16le(d, 0x5a),
      gems: u16le(d, 0x5c),
      hpMax: u16le(d, 0x5e),
      hpTemp: u16le(d, 0x60),
      experience: u32le(d, 0x62),
      gold: u32le(d, 0x66),
      baseAlignment: d[0x6a],
      baseStats: {
        might: d[0x6b],
        intelligence: d[0x6c],
        personality: d[0x6d],
        speed: d[0x6e],
        accuracy: d[0x6f],
        luck: d[0x70],
      },
      level: d[0x71],
      secondaryLevel: d[0x72],
      baseEndurance: d[0x73],
      hpCurrent: u16le(d, 0x74),
      tempWord: u16le(d, 0x76),
      scriptFlag: d[0x78],
      classQuestMask: d[0x79],
      tail: Uint8Array.from(d.subarray(0x7a, 0x82)),
    });
  }
  return {
    characters,
    global: Uint8Array.from(data.subarray(ROSTER_CHAR_COUNT * ROSTER_CHAR_RECORD_SIZE, ROSTER_FILE_SIZE)),
  };
}

export function encodeRoster(roster: RosterFile): Uint8Array {
  const out = new Uint8Array(ROSTER_FILE_SIZE);
  for (let i = 0; i < ROSTER_CHAR_COUNT; i++) {
    const c = roster.characters[i];
    const off = i * ROSTER_CHAR_RECORD_SIZE;
    // Preserve the original name-field bytes when the name is unchanged;
    // otherwise re-pad with spaces (the doc's other padding convention).
    // eslint-disable-next-line no-control-regex
    const rawName = new TextDecoder('latin1').decode(c.nameRaw).replace(/[\u0000 ]+$/, '');
    if (rawName === c.name) {
      out.set(c.nameRaw, off);
    } else {
      const nameBytes = new TextEncoder().encode(c.name);
      if (nameBytes.length > 11) throw new Error(`character name too long: "${c.name}"`);
      out.fill(0x20, off, off + 11);
      out.set(nameBytes, off);
    }
    out[off + 0x0b] = (c.town & 0x7f) | (c.inParty ? 0x80 : 0x00);
    out[off + 0x0c] = c.sex;
    out[off + 0x0d] = c.alignment;
    out[off + 0x0e] = c.race;
    out[off + 0x0f] = c.charClass;
    out[off + 0x10] = c.stats.might;
    out[off + 0x11] = c.stats.intelligence;
    out[off + 0x12] = c.stats.personality;
    out[off + 0x13] = c.stats.speed;
    out[off + 0x14] = c.stats.accuracy;
    out[off + 0x15] = c.stats.luck;
    out[off + 0x16] = c.thievery;
    out.set(c.skills, off + 0x17);
    out.set(c.questFlags, off + 0x1a);
    out[off + 0x20] = c.workingLevel;
    out[off + 0x21] = c.age;
    out[off + 0x22] = c.unknown22;
    out[off + 0x23] = c.workingSpellLevel;
    out[off + 0x24] = c.armorClass;
    out[off + 0x25] = c.food;
    out[off + 0x26] = c.condition;
    out[off + 0x27] = c.endurance;
    out.set(c.equipped.ids, off + 0x28);
    out.set(c.equipped.charges, off + 0x2e);
    out.set(c.equipped.flags, off + 0x34);
    out.set(c.backpack.ids, off + 0x3a);
    out.set(c.backpack.charges, off + 0x40);
    out.set(c.backpack.flags, off + 0x46);
    out.set(c.spellBook, off + 0x4c);
    const w = (o: number, v: number) => {
      out[off + o] = v & 0xff;
      out[off + o + 1] = (v >> 8) & 0xff;
    };
    w(0x58, c.spMax);
    w(0x5a, c.spCurrent);
    w(0x5c, c.gems);
    w(0x5e, c.hpMax);
    w(0x60, c.hpTemp);
    const l = (o: number, v: number) => {
      out[off + o] = v & 0xff;
      out[off + o + 1] = (v >> 8) & 0xff;
      out[off + o + 2] = (v >> 16) & 0xff;
      out[off + o + 3] = (v >>> 24) & 0xff;
    };
    l(0x62, c.experience);
    l(0x66, c.gold);
    out[off + 0x6a] = c.baseAlignment;
    out[off + 0x6b] = c.baseStats.might;
    out[off + 0x6c] = c.baseStats.intelligence;
    out[off + 0x6d] = c.baseStats.personality;
    out[off + 0x6e] = c.baseStats.speed;
    out[off + 0x6f] = c.baseStats.accuracy;
    out[off + 0x70] = c.baseStats.luck;
    out[off + 0x71] = c.level;
    out[off + 0x72] = c.secondaryLevel;
    out[off + 0x73] = c.baseEndurance;
    w(0x74, c.hpCurrent);
    w(0x76, c.tempWord);
    out[off + 0x78] = c.scriptFlag;
    out[off + 0x79] = c.classQuestMask;
    out.set(c.tail, off + 0x7a);
  }
  out.set(roster.global, ROSTER_CHAR_COUNT * ROSTER_CHAR_RECORD_SIZE);
  return out;
}

export const ROSTER_RACES: Record<number, string> = {
  0: 'Human', 1: 'Elf', 2: 'Dwarf', 3: 'Gnome', 4: 'Half-Orc',
};

export const ROSTER_CLASSES: Record<number, string> = {
  0: 'Knight', 1: 'Paladin', 2: 'Archer', 3: 'Cleric', 4: 'Sorcerer', 5: 'Robber', 6: 'Ninja', 7: 'Barbarian',
};

export const ROSTER_TOWNS: Record<number, string> = {
  1: 'Middlegate', 2: 'Atlantium', 3: 'Tundara', 4: 'Vulcania', 5: 'Sandsobar',
};

export const ROSTER_CONDITIONS: Record<number, string> = {
  0: 'Good', 1: 'Cursed', 2: 'Silenced', 3: 'Silenced', 4: 'Poisoned',
};

export function conditionName(code: number): string {
  if ((code & 0x80) !== 0) return 'Dead/Stone/Eradicated';
  return ROSTER_CONDITIONS[code] ?? `Unknown (${code})`;
}
