"""Shared decoding helpers for the Black Crypt extractors.

Before this package existed, `rle_decompress` was copy-pasted into twelve
scripts and the planar decoder into four, each with small drifts. Everything
here has a single definition; import it rather than re-deriving it.
"""
from .rle import rle_decompress, rle_decompress_end, rle_streams, MONSTER_STREAM_START
from . import bcdfv
from . import bcdfs
from .bcdfxyz import (
    CHUNK_DIRECTORIES,
    SLOT_SIZES,
    SUB_IMAGES,
    SUB_IMAGE_COUNT,
    read_chunk_directory,
    read_chunks,
    iter_sub_images,
)
from .bcdfa import (
    CONTAINER_DIRECTORY,
    SLOT_UI_PANEL,
    SLOT_PAPERDOLL,
    SLOT_SFX,
    SLOT_GFK,
    SLOT_FONT,
    SLOT_TEXT_RESOURCE,
    SLOT_EFF,
    SLOT_PRG,
    SLOT_ITEM_BANK0,
    SLOT_FLOOR_ITEMS,
    SLOT_ARMOUR,
    SLOT_ITEM_BANK1,
    SLOT_THROWING_ITEMS,
    SLOT_UNKNOWN_TAIL,
    read_container_directory,
    read_container_chunks,
    FONT_MONO_OFFSET,
    FONT_MONO_WIDTH,
    FONT_MONO_HEIGHT,
    FONT_MONO_GLYPH_BYTES,
    FONT_MONO_COUNT,
    FONT_REGION_A_OFFSET,
    FONT_REGION_A_WIDTH,
    FONT_REGION_A_HEIGHT,
    FONT_REGION_A_GLYPH_BYTES,
    FONT_REGION_A_COUNT,
    FONT_REGION_B_OFFSET,
    FONT_REGION_B_WIDTH,
    FONT_REGION_B_HEIGHT,
    FONT_REGION_B_GLYPH_BYTES,
    FONT_REGION_B_COUNT,
    FONT_REGION_C_OFFSET,
    FONT_REGION_C_WIDTH,
    FONT_REGION_C_HEIGHT,
    FONT_REGION_C_GLYPH_BYTES,
    FONT_REGION_C_COUNT,
    FONT_REGION_D_OFFSET,
    FONT_REGION_D_WIDTH,
    FONT_REGION_D_HEIGHT,
    FONT_REGION_D_COLOR_PLANES,
    FONT_REGION_D_GLYPH_BYTES,
    FONT_REGION_D_COUNT,
    FONT_CHUNK_BYTES,
    mono_font_glyphs,
    font_micro_glyphs,
    font_big_glyphs,
    KEY_ICON_OFFSET,
    KEY_ICON_WIDTH,
    KEY_ICON_HEIGHT,
    KEY_ICON_COLOR_PLANES,
    KEY_ICON_RECORD_BYTES,
    KEY_ICON_COUNT,
    KEY_ICON_BACKDROP_INDEX,
    KEY_ICON_GFX_BASE,
    key_icon_sprites,
    SPELL_BOOK_OFFSET,
    SPELL_BOOK_WIDTH,
    SPELL_BOOK_HEIGHT,
    SPELL_BOOK_COLOR_PLANES,
    SPELL_BOOK_BYTES,
    spell_book_background,
    TEXT_RESOURCE_BYTES,
    TEXT_RESOURCE_LAYOUT,
    check_text_resource_layout,
    PANEL_WIDTH,
    PANEL_COLOR_PLANES,
    PANEL_SCREEN_BYTE_X,
    STONE_PANEL_OFFSET,
    STONE_PANEL_HEIGHT,
    STONE_PANEL_BYTES,
    STONE_PANEL_DOS_ORIGIN,
    STONE_PANEL_CASTOR_ORIGIN,
    PANEL_CLEAR_STRIP_OFFSET,
    PANEL_CLEAR_STRIP_HEIGHT,
    PANEL_CLEAR_STRIP_BYTES,
    SCROLL_TOP_OFFSET,
    SCROLL_TOP_HEIGHT,
    SCROLL_TOP_BYTES,
    SCROLL_PIECE_OFFSET,
    SCROLL_PIECE_HEIGHT,
    SCROLL_PIECE_BYTES,
    SCROLL_PIECE_REPEAT,
    SCROLL_PIECE_SCREEN_ROW,
    SCROLL_DOS_X_ORIGIN,
    FIRE_ANIMATION_OFFSET,
    FIRE_ANIMATION_WIDTH,
    FIRE_ANIMATION_STORED_HEIGHT,
    FIRE_ANIMATION_HEIGHT,
    FIRE_ANIMATION_COLOR_PLANES,
    FIRE_ANIMATION_FRAME_BYTES,
    FIRE_ANIMATION_COUNT,
    FIRE_ANIMATION_POSITIONS,
    FIRE_ANIMATION_PERIOD,
    FIRE_ANIMATION_TICKS_PER_FRAME,
    FIRE_ANIMATION_PHASES,
    FIRE_ANIMATION_BACKDROP_INDEX,
    SPRITE_RECORD_BYTES,
    SPRITE_RECORDS_PER_BANK,
    SPRITE_WIDTH,
    MOUSE_POINTER_OFFSET,
    MOUSE_POINTER_LINES,
    MOUSE_POINTER_BYTES,
    BUBBLE_OFFSET,
    BUBBLE_LINES,
    BUBBLE_BYTES,
    AUTOMAP_BLOCK_OFFSET,
    AUTOMAP_BLOCK_WIDTH,
    AUTOMAP_BLOCK_HEIGHT,
    AUTOMAP_BLOCK_PLANES,
    AUTOMAP_BLOCK_BYTES,
    AUTOMAP_BLOCK_COLOR_BASE,
    AUTOMAP_GRID_COLUMNS,
    AUTOMAP_TILE_OFFSET,
    AUTOMAP_TILE_SIZE,
    AUTOMAP_TILE_PLANES,
    AUTOMAP_TILE_BYTES,
    AUTOMAP_TILE_COUNT,
    AUTOMAP_TILE_BANK_BYTES,
    TREASURE_CHEST_OFFSET,
    TREASURE_CHEST_WIDTH,
    TREASURE_CHEST_HEIGHT,
    TREASURE_CHEST_COLOR_PLANES,
    TREASURE_CHEST_RECORD_BYTES,
    TREASURE_CHEST_COUNT,
    TREASURE_CHEST_SCREEN_XY,
    TREASURE_CHEST_DOS_X_ORIGIN,
    stone_panel,
    panel_clear_strip,
    scroll_top,
    scroll_piece,
    scroll_panel,
    fire_animation_frames,
    mouse_pointer_sprite,
    bubble_sprite,
    automap_block,
    automap_tiles,
    treasure_chest_sprites,
    EFF_STREAM,
    EFF_STREAM_END,
    EFF_BANK_BYTES,
    EFF_TABLE,
    EFF_COUNT,
    EFF_RECORD_BYTES,
    EFF_GROUP_TERMINATOR,
    eff_table_offsets,
    eff_scripts,
    PRG_TAG_KILL,
    PRG_TAG_NEXT_FRAME,
    PRG_TAG_PREV_FRAME,
    PRG_TAG_DXDY_ONLY,
    PRG_TAG_ABSOLUTE_FRAME_MAX,
    EFF_FRAME_COUNT_TABLE,
    EFF_FRAME_COUNT_TABLE_LEN,
    EFF_VIEWPORT_WIDTH,
    EFF_VIEWPORT_HEIGHT,
    EFF_SPRITE_SIZE,
    EFF_KILL_X_MAX,
    EFF_KILL_Y_MAX,
    EFF_MAX_TRAILING_TICKS,
    gfk_frame_counts,
    simulate_effect,
    GFK_MARKER,
    PRG_MARKER,
    GFK_FRAME_BYTES,
    GFK_WIDTH,
    GFK_HEIGHT,
    GFK_COLOR_PLANES,
    gfk_stream_start,
    gfk_records,
    gfk_frames,
    prg_records,
    ITEM_WIDTH,
    ITEM_HEIGHT,
    ITEM_COLOR_PLANES,
    ITEM_ICON_BYTES,
    ITEM_BANK_STREAMS,
    ITEM_BACKDROP_INDEX,
    ITEM_TYPE_NAMES,
    item_icons,
    ARMOUR_WIDTH,
    ARMOUR_HEIGHT,
    ARMOUR_COLOR_PLANES,
    ARMOUR_RECORD_BYTES,
    ARMOUR_STREAM,
    ARMOUR_BACKDROP_INDEX,
    armour_icons,
    PAPERDOLL_STREAM,
    PAPERDOLL_STORAGE_WIDTH,
    PAPERDOLL_WIDTH,
    PAPERDOLL_COLOR_PLANES,
    PAPERDOLL_BACKDROP_INDEX,
    PAPERDOLL_RECORDS,
    paperdoll_records,
    FLOOR_ITEM_STREAM,
    FLOOR_ITEM_BANK_BYTES,
    FLOOR_ITEM_TABLE,
    FLOOR_ITEM_GROUPS,
    FLOOR_ITEM_DEPTHS,
    FLOOR_ITEM_COUNT,
    FLOOR_ITEM_PLANES,
    FLOOR_ITEM_GFX_TABLE,
    FLOOR_ITEM_GFX_TABLE_LEN,
    FLOOR_ITEM_GFX_NONE,
    FLOOR_ITEM_NAMES,
    floor_item_descriptors,
    floor_item_sprites,
    floor_item_gfx_table,
    UI_PANEL_STREAM,
    UI_PANEL_COLOR_PLANES,
    UI_PANEL_RECORDS,
    ui_panel_stream,
    ui_panel_records,
    SFX_BANK_START,
    SFX_BANK_END,
    SFX_RECORDS,
    sfx_samples,
    THROWING_ITEM_COLOR_PLANES,
    THROWING_ITEM_RECORDS,
    throwing_item_sprites,
)
from .planar import (decode_planar, decode_masked, decode_sprite_pair,
                     decode_stencil, stencil_to_rgba, to_rgba)
from .palette import (
    BCDFQ_PALETTES,
    BCDFP_CHARGEN_PALETTE,
    BCDFU_DUNGEON_PALETTES,
    BCDFU_TAN_SANDSTONE,
    BCDFT_DUNGEON_PALETTE,
    BCDFT_AUTOMAP_PALETTE,
    AUTOMAP_PLAYFIELD2_COLOR_BASE,
    BCDFT_ACCENT_RAMPS,
    BCDFT_ACCENT_RAMP_COUNT,
    BCDFT_LEVEL_RAMP_TABLE,
    DUNGEON_LEVELS,
    SQUARE_FLAG_RAMP,
    read_chargen_palette,
    read_dungeon_palette,
    read_accent_ramp,
    read_level_ramp_indices,
    read_dungeon_palette_for_level,
    read_level_tileset_indices,
    tileset_levels,
    tileset_ramps,
    read_dungeon_palette_for_tileset,
    TILESET_FILES,
    amiga12_to_rgb,
    read_palette_words,
    read_named_palette,
    ehb_palette,
    load_palette_json,
)
from .atlas import pack_atlas, frames_to_json, Frame
from .paths import (
    ROOT,
    asset_root,
    asset_dir,
    cache_dir,
    data_dir,
    write_atlas,
    write_json,
    write_png,
    write_manifest,
    write_platform_index,
    manifest_entry,
    set_groups_file,
)

__all__ = [
    'rle_decompress', 'rle_decompress_end', 'rle_streams', 'MONSTER_STREAM_START',
    'bcdfv',
    'CHUNK_DIRECTORIES', 'SLOT_SIZES', 'SUB_IMAGES', 'SUB_IMAGE_COUNT',
    'read_chunk_directory', 'read_chunks', 'iter_sub_images',
    'CONTAINER_DIRECTORY', 'SLOT_UI_PANEL', 'SLOT_PAPERDOLL', 'SLOT_SFX',
    'SLOT_GFK', 'SLOT_FONT', 'SLOT_TEXT_RESOURCE', 'SLOT_EFF',
    'SLOT_PRG', 'SLOT_ITEM_BANK0', 'SLOT_FLOOR_ITEMS', 'SLOT_ARMOUR',
    'SLOT_ITEM_BANK1', 'SLOT_THROWING_ITEMS', 'SLOT_UNKNOWN_TAIL',
    'read_container_directory', 'read_container_chunks',
    'FONT_MONO_OFFSET', 'FONT_MONO_WIDTH', 'FONT_MONO_HEIGHT',
    'FONT_MONO_GLYPH_BYTES', 'FONT_MONO_COUNT',
    'FONT_REGION_A_OFFSET', 'FONT_REGION_A_WIDTH', 'FONT_REGION_A_HEIGHT',
    'FONT_REGION_A_GLYPH_BYTES', 'FONT_REGION_A_COUNT',
    'FONT_REGION_B_OFFSET', 'FONT_REGION_B_WIDTH', 'FONT_REGION_B_HEIGHT',
    'FONT_REGION_B_GLYPH_BYTES', 'FONT_REGION_B_COUNT',
    'FONT_REGION_C_OFFSET', 'FONT_REGION_C_WIDTH', 'FONT_REGION_C_HEIGHT',
    'FONT_REGION_C_GLYPH_BYTES', 'FONT_REGION_C_COUNT',
    'FONT_REGION_D_OFFSET', 'FONT_REGION_D_WIDTH', 'FONT_REGION_D_HEIGHT',
    'FONT_REGION_D_COLOR_PLANES', 'FONT_REGION_D_GLYPH_BYTES',
    'FONT_REGION_D_COUNT', 'FONT_CHUNK_BYTES',
    'mono_font_glyphs', 'font_micro_glyphs', 'font_big_glyphs',
    'KEY_ICON_OFFSET', 'KEY_ICON_WIDTH', 'KEY_ICON_HEIGHT',
    'KEY_ICON_COLOR_PLANES', 'KEY_ICON_RECORD_BYTES', 'KEY_ICON_COUNT',
    'KEY_ICON_BACKDROP_INDEX', 'KEY_ICON_GFX_BASE', 'key_icon_sprites',
    'SPELL_BOOK_OFFSET', 'SPELL_BOOK_WIDTH', 'SPELL_BOOK_HEIGHT',
    'SPELL_BOOK_COLOR_PLANES', 'SPELL_BOOK_BYTES', 'spell_book_background',
    'TEXT_RESOURCE_BYTES', 'TEXT_RESOURCE_LAYOUT', 'check_text_resource_layout',
    'PANEL_WIDTH', 'PANEL_COLOR_PLANES', 'PANEL_SCREEN_BYTE_X',
    'STONE_PANEL_OFFSET', 'STONE_PANEL_HEIGHT', 'STONE_PANEL_BYTES',
    'STONE_PANEL_DOS_ORIGIN', 'STONE_PANEL_CASTOR_ORIGIN',
    'PANEL_CLEAR_STRIP_OFFSET', 'PANEL_CLEAR_STRIP_HEIGHT',
    'PANEL_CLEAR_STRIP_BYTES',
    'SCROLL_TOP_OFFSET', 'SCROLL_TOP_HEIGHT', 'SCROLL_TOP_BYTES',
    'SCROLL_PIECE_OFFSET', 'SCROLL_PIECE_HEIGHT', 'SCROLL_PIECE_BYTES',
    'SCROLL_PIECE_REPEAT', 'SCROLL_PIECE_SCREEN_ROW', 'SCROLL_DOS_X_ORIGIN',
    'FIRE_ANIMATION_OFFSET', 'FIRE_ANIMATION_WIDTH',
    'FIRE_ANIMATION_STORED_HEIGHT', 'FIRE_ANIMATION_HEIGHT',
    'FIRE_ANIMATION_COLOR_PLANES', 'FIRE_ANIMATION_FRAME_BYTES',
    'FIRE_ANIMATION_COUNT', 'FIRE_ANIMATION_POSITIONS', 'FIRE_ANIMATION_PERIOD',
    'FIRE_ANIMATION_TICKS_PER_FRAME', 'FIRE_ANIMATION_PHASES',
    'FIRE_ANIMATION_BACKDROP_INDEX',
    'SPRITE_RECORD_BYTES', 'SPRITE_RECORDS_PER_BANK', 'SPRITE_WIDTH',
    'MOUSE_POINTER_OFFSET', 'MOUSE_POINTER_LINES', 'MOUSE_POINTER_BYTES',
    'BUBBLE_OFFSET', 'BUBBLE_LINES', 'BUBBLE_BYTES',
    'AUTOMAP_BLOCK_OFFSET', 'AUTOMAP_BLOCK_WIDTH', 'AUTOMAP_BLOCK_HEIGHT',
    'AUTOMAP_BLOCK_PLANES', 'AUTOMAP_BLOCK_BYTES', 'AUTOMAP_BLOCK_COLOR_BASE',
    'AUTOMAP_GRID_COLUMNS',
    'AUTOMAP_TILE_OFFSET', 'AUTOMAP_TILE_SIZE', 'AUTOMAP_TILE_PLANES',
    'AUTOMAP_TILE_BYTES', 'AUTOMAP_TILE_COUNT', 'AUTOMAP_TILE_BANK_BYTES',
    'TREASURE_CHEST_OFFSET', 'TREASURE_CHEST_WIDTH', 'TREASURE_CHEST_HEIGHT',
    'TREASURE_CHEST_COLOR_PLANES', 'TREASURE_CHEST_RECORD_BYTES',
    'TREASURE_CHEST_COUNT', 'TREASURE_CHEST_SCREEN_XY',
    'TREASURE_CHEST_DOS_X_ORIGIN',
    'stone_panel', 'panel_clear_strip', 'scroll_top', 'scroll_piece',
    'scroll_panel', 'fire_animation_frames', 'mouse_pointer_sprite',
    'bubble_sprite', 'automap_block', 'automap_tiles', 'treasure_chest_sprites',
    'EFF_STREAM', 'EFF_STREAM_END', 'EFF_BANK_BYTES', 'EFF_TABLE',
    'EFF_COUNT', 'EFF_RECORD_BYTES', 'EFF_GROUP_TERMINATOR',
    'eff_table_offsets', 'eff_scripts',
    'PRG_TAG_KILL', 'PRG_TAG_NEXT_FRAME', 'PRG_TAG_PREV_FRAME',
    'PRG_TAG_DXDY_ONLY', 'PRG_TAG_ABSOLUTE_FRAME_MAX',
    'EFF_FRAME_COUNT_TABLE', 'EFF_FRAME_COUNT_TABLE_LEN',
    'EFF_VIEWPORT_WIDTH', 'EFF_VIEWPORT_HEIGHT', 'EFF_SPRITE_SIZE',
    'EFF_KILL_X_MAX', 'EFF_KILL_Y_MAX', 'EFF_MAX_TRAILING_TICKS',
    'gfk_frame_counts', 'simulate_effect',
    'GFK_MARKER', 'PRG_MARKER', 'GFK_FRAME_BYTES', 'GFK_WIDTH', 'GFK_HEIGHT',
    'GFK_COLOR_PLANES', 'gfk_stream_start', 'gfk_records', 'gfk_frames',
    'prg_records',
    'ITEM_WIDTH', 'ITEM_HEIGHT', 'ITEM_COLOR_PLANES', 'ITEM_ICON_BYTES',
    'ITEM_BANK_STREAMS', 'ITEM_BACKDROP_INDEX', 'ITEM_TYPE_NAMES', 'item_icons',
    'ARMOUR_WIDTH', 'ARMOUR_HEIGHT', 'ARMOUR_COLOR_PLANES',
    'ARMOUR_RECORD_BYTES', 'ARMOUR_STREAM', 'ARMOUR_BACKDROP_INDEX',
    'armour_icons',
    'PAPERDOLL_STREAM', 'PAPERDOLL_STORAGE_WIDTH', 'PAPERDOLL_WIDTH',
    'PAPERDOLL_COLOR_PLANES', 'PAPERDOLL_BACKDROP_INDEX',
    'PAPERDOLL_RECORDS', 'paperdoll_records',
    'FLOOR_ITEM_STREAM', 'FLOOR_ITEM_BANK_BYTES', 'FLOOR_ITEM_TABLE',
    'FLOOR_ITEM_GROUPS', 'FLOOR_ITEM_DEPTHS', 'FLOOR_ITEM_COUNT',
    'FLOOR_ITEM_PLANES', 'FLOOR_ITEM_GFX_TABLE', 'FLOOR_ITEM_GFX_TABLE_LEN',
    'FLOOR_ITEM_GFX_NONE', 'FLOOR_ITEM_NAMES', 'floor_item_descriptors',
    'floor_item_sprites', 'floor_item_gfx_table',
    'UI_PANEL_STREAM', 'UI_PANEL_COLOR_PLANES', 'UI_PANEL_RECORDS',
    'ui_panel_stream', 'ui_panel_records',
    'SFX_BANK_START', 'SFX_BANK_END', 'SFX_RECORDS', 'sfx_samples',
    'THROWING_ITEM_COLOR_PLANES', 'THROWING_ITEM_RECORDS',
    'throwing_item_sprites',
    'decode_planar', 'decode_masked', 'decode_sprite_pair',
    'decode_stencil', 'stencil_to_rgba', 'to_rgba',
    'BCDFQ_PALETTES', 'BCDFP_CHARGEN_PALETTE', 'BCDFU_DUNGEON_PALETTES', 'BCDFU_TAN_SANDSTONE',
    'BCDFT_DUNGEON_PALETTE', 'BCDFT_AUTOMAP_PALETTE',
    'AUTOMAP_PLAYFIELD2_COLOR_BASE',
    'BCDFT_ACCENT_RAMPS', 'BCDFT_ACCENT_RAMP_COUNT',
    'BCDFT_LEVEL_RAMP_TABLE', 'DUNGEON_LEVELS', 'SQUARE_FLAG_RAMP',
    'read_chargen_palette', 'read_dungeon_palette', 'read_accent_ramp', 'read_level_ramp_indices',
    'read_dungeon_palette_for_level', 'amiga12_to_rgb', 'read_palette_words',
    'read_level_tileset_indices', 'tileset_levels', 'tileset_ramps',
    'read_dungeon_palette_for_tileset', 'TILESET_FILES',
    'read_named_palette', 'ehb_palette', 'load_palette_json',
    'pack_atlas', 'frames_to_json', 'Frame',
    'ROOT', 'asset_root', 'asset_dir', 'cache_dir', 'data_dir',
    'write_atlas', 'write_json', 'write_png', 'write_manifest', 'set_groups_file',
    'write_platform_index', 'manifest_entry',
]
